### ISSUE TITLE
(1.12.2) Panes look different based on how you view them

### ISSUE THREAD

**Issue by Alaberti** [Chisel-Team/CTM-Resources#3] opened 2017-11-29 01:33 UTC
- ctp_1.2_MCv3
-CTM-MC1.12-0.2.3.9

Optifine is NOT installed. 

![2017-11-28_19 31 30](https://user-images.githubusercontent.com/10929796/33353319-dafbd23a-d472-11e7-8c19-09943a75409c.png)
![2017-11-28_19 31 39](https://user-images.githubusercontent.com/10929796/33353320-db0912d8-d472-11e7-952e-43acc81ca371.png)
![2017-11-28_19 31 46](https://user-images.githubusercontent.com/10929796/33353321-db1ae68e-d472-11e7-8f08-6038ec8d864c.png)
![2017-11-28_19 31 51](https://user-images.githubusercontent.com/10929796/33353322-db2ca82e-d472-11e7-9787-71c99e33a58e.png)

**Comment by Alaberti** [comment] 2017-11-30 00:19
Oh closed it because because it was previously reported on the ctm mod tracker

**Comment by Alaberti** [comment] 2018-04-27 17:13
Is it safe to assume this won't be fixed or doesn't have a fix action being worked on?

**Comment by tterrag1098** [comment] 2018-04-27 17:27
They will be fixed next update https://github.com/Chisel-Team/ConnectedTexturesPack/commit/1dd89963b49333654519652fef39db44b5ab530c

**Comment by Alaberti** [comment] 2018-04-28 00:30
Thank you for the update!

**Comment by Alaberti** [comment] 2018-06-22 01:23
Erm, any chance an update could be pushed? I don't want to be "that guy"

**Closed as completed** 2018-11-01 02:28 UTC

**Comment by VincentLongiug** [comment] 2019-08-15 14:27
If you're still looking for a simple solution @Alaberti, you can just copy the pane_side.json and pane_side_alt.json from the minecraft/models/block folder into your ressource pack and proceed the following modifications : 
- In pane_side.json : **"west":  { "uv": [ 16, 0,  9, 16 ], "texture": "#pane" },** 
become **"west":  { "uv": [ 0, 0,  7, 16 ], "texture": "#pane" },**
- In pane_side_alt.json : **"west":  { "uv": [  7, 0,  0, 16 ], "texture": "#pane" },** 
become **"west":  { "uv": [  9, 0,  16, 16 ], "texture": "#pane" },**

The only remaining problems are the edges inside a tall window (pack improvement feature) and the disconnected textures between panes which make corners and those who are straight (bug in the mod : issue reported [here](https://github.com/Chisel-Team/ConnectedTexturesMod/issues/107))
![2019-08-15_16 17 09](https://user-images.githubusercontent.com/52882424/63101356-2e491400-bf79-11e9-9344-8f5b2a33e234.png)

**Comment by PurplePrint** [comment] 2024-10-18 08:51
The problem is still relevant.
![2024-10-18_11 36 30](https://github.com/user-attachments/assets/6fcd3aaf-15d7-47e5-a0b3-3b612bb93bbb)
